<?php

/* node_modules/repeat-element/README.md */
class __TwigTemplate_bed47c94745cd425fd5dca1a02478f79500a7b466548424aefeb38a510868bcb extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_06d45b9bc2c52fc2ac676ac19b19a078c6b09b57341382b08d33b784de8d612b = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_06d45b9bc2c52fc2ac676ac19b19a078c6b09b57341382b08d33b784de8d612b->enter($__internal_06d45b9bc2c52fc2ac676ac19b19a078c6b09b57341382b08d33b784de8d612b_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/repeat-element/README.md"));

        // line 1
        echo "# repeat-element [![NPM version](https://badge.fury.io/js/repeat-element.svg)](http://badge.fury.io/js/repeat-element)

> Create an array by repeating the given value n times.

## Install

Install with [npm](https://www.npmjs.com/)

```bash
npm i repeat-element --save
```

## Usage

```js
var repeat = require('repeat-element');

repeat('a', 5);
//=> ['a', 'a', 'a', 'a', 'a']

repeat('a', 1);
//=> ['a']

repeat('a', 0);
//=> []

repeat(null, 5)
//» [ null, null, null, null, null ]

repeat({some: 'object'}, 5)
//» [ { some: 'object' },
//    { some: 'object' },
//    { some: 'object' },
//    { some: 'object' },
//    { some: 'object' } ]

repeat(5, 5)
//» [ 5, 5, 5, 5, 5 ]
```

## Related projects

[repeat-string](https://github.com/jonschlinkert/repeat-string): Repeat the given string n times. Fastest implementation for repeating a string.

## Running tests

Install dev dependencies:

```bash
npm i -d && npm test
```

## Contributing

Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/repeat-element/issues)

## Author

**Jon Schlinkert**

+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert)

## License

Copyright (c) 2015 Jon Schlinkert
Released under the MIT license.

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on May 06, 2015._
";
        
        $__internal_06d45b9bc2c52fc2ac676ac19b19a078c6b09b57341382b08d33b784de8d612b->leave($__internal_06d45b9bc2c52fc2ac676ac19b19a078c6b09b57341382b08d33b784de8d612b_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/repeat-element/README.md";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# repeat-element [![NPM version](https://badge.fury.io/js/repeat-element.svg)](http://badge.fury.io/js/repeat-element)

> Create an array by repeating the given value n times.

## Install

Install with [npm](https://www.npmjs.com/)

```bash
npm i repeat-element --save
```

## Usage

```js
var repeat = require('repeat-element');

repeat('a', 5);
//=> ['a', 'a', 'a', 'a', 'a']

repeat('a', 1);
//=> ['a']

repeat('a', 0);
//=> []

repeat(null, 5)
//» [ null, null, null, null, null ]

repeat({some: 'object'}, 5)
//» [ { some: 'object' },
//    { some: 'object' },
//    { some: 'object' },
//    { some: 'object' },
//    { some: 'object' } ]

repeat(5, 5)
//» [ 5, 5, 5, 5, 5 ]
```

## Related projects

[repeat-string](https://github.com/jonschlinkert/repeat-string): Repeat the given string n times. Fastest implementation for repeating a string.

## Running tests

Install dev dependencies:

```bash
npm i -d && npm test
```

## Contributing

Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/repeat-element/issues)

## Author

**Jon Schlinkert**

+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert)

## License

Copyright (c) 2015 Jon Schlinkert
Released under the MIT license.

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on May 06, 2015._
", "node_modules/repeat-element/README.md", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/repeat-element/README.md");
    }
}
