<?php

/* node_modules/longest/README.md */
class __TwigTemplate_1f8f78a9e2a3db305cd1accea0eef7662e22977dc5745732178c6fa9cf8db06c extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_f4cef6bc6f63fd38cfbafaef3a687d27c4c747e019c64dd0553c569c0af22301 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_f4cef6bc6f63fd38cfbafaef3a687d27c4c747e019c64dd0553c569c0af22301->enter($__internal_f4cef6bc6f63fd38cfbafaef3a687d27c4c747e019c64dd0553c569c0af22301_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/longest/README.md"));

        // line 1
        echo "# longest [![NPM version](https://badge.fury.io/js/longest.svg)](http://badge.fury.io/js/longest)  [![Build Status](https://travis-ci.org/jonschlinkert/longest.svg)](https://travis-ci.org/jonschlinkert/longest) 

> Get the longest item in an array.

## Install with [npm](npmjs.org)

```bash
npm i longest --save
```
### Install with [bower](https://github.com/bower/bower)

```bash
bower install longest --save
```

## Running tests
Install dev dependencies.

```bash
npm i -d && npm test
```

## Usage

```js
var longest = require('longest');
longest(['a', 'abcde', 'abc']);
//=> 'abcde'

longest(['a', 'abcde', 'abc']).length;
//=> 5
```

## Related projects
* [longest-value](https://github.com/jonschlinkert/longest-value): Get the longest value for the given property from an array of objects. Useful for aligning values.
* [right-align-values](https://github.com/jonschlinkert/right-align-values): Right align the values of a given property for each object in an array. Useful for creating text columns or tables.
* [right-pad-values](https://github.com/jonschlinkert/right-pad-values): Right pad the values of a given property for each object in an array. Useful for creating text columns or tables.
* [repeat-string](https://github.com/jonschlinkert/repeat-string): Repeat the given string n times. Fastest implementation for repeating a string.
* [pad-right](https://github.com/jonschlinkert/pad-right): Right pad a string with zeros or a specified string. Fastest implementation.
* [pad-left](https://github.com/jonschlinkert/pad-left): Left pad a string with zeros or a specified string. Fastest implementation.  

## Running tests
Install dev dependencies.

```bash
npm i -d && npm test
```

## Contributing
Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/longest/issues)

## Author

**Jon Schlinkert**
 
+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert) 

## License
Copyright (c) 2015 Jon Schlinkert  
Released under the MIT license

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on March 31, 2015._";
        
        $__internal_f4cef6bc6f63fd38cfbafaef3a687d27c4c747e019c64dd0553c569c0af22301->leave($__internal_f4cef6bc6f63fd38cfbafaef3a687d27c4c747e019c64dd0553c569c0af22301_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/longest/README.md";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# longest [![NPM version](https://badge.fury.io/js/longest.svg)](http://badge.fury.io/js/longest)  [![Build Status](https://travis-ci.org/jonschlinkert/longest.svg)](https://travis-ci.org/jonschlinkert/longest) 

> Get the longest item in an array.

## Install with [npm](npmjs.org)

```bash
npm i longest --save
```
### Install with [bower](https://github.com/bower/bower)

```bash
bower install longest --save
```

## Running tests
Install dev dependencies.

```bash
npm i -d && npm test
```

## Usage

```js
var longest = require('longest');
longest(['a', 'abcde', 'abc']);
//=> 'abcde'

longest(['a', 'abcde', 'abc']).length;
//=> 5
```

## Related projects
* [longest-value](https://github.com/jonschlinkert/longest-value): Get the longest value for the given property from an array of objects. Useful for aligning values.
* [right-align-values](https://github.com/jonschlinkert/right-align-values): Right align the values of a given property for each object in an array. Useful for creating text columns or tables.
* [right-pad-values](https://github.com/jonschlinkert/right-pad-values): Right pad the values of a given property for each object in an array. Useful for creating text columns or tables.
* [repeat-string](https://github.com/jonschlinkert/repeat-string): Repeat the given string n times. Fastest implementation for repeating a string.
* [pad-right](https://github.com/jonschlinkert/pad-right): Right pad a string with zeros or a specified string. Fastest implementation.
* [pad-left](https://github.com/jonschlinkert/pad-left): Left pad a string with zeros or a specified string. Fastest implementation.  

## Running tests
Install dev dependencies.

```bash
npm i -d && npm test
```

## Contributing
Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/longest/issues)

## Author

**Jon Schlinkert**
 
+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert) 

## License
Copyright (c) 2015 Jon Schlinkert  
Released under the MIT license

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on March 31, 2015._", "node_modules/longest/README.md", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/longest/README.md");
    }
}
