<?php

/* node_modules/preserve/README.md */
class __TwigTemplate_5fb5a0265be11b98c8c84704df2b2059a5a624de87730a657a57c52098b2c200 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_131d38353579464d037a76dbc314b6ea6f799d1fd88cde254d32923e8b1e8a7b = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_131d38353579464d037a76dbc314b6ea6f799d1fd88cde254d32923e8b1e8a7b->enter($__internal_131d38353579464d037a76dbc314b6ea6f799d1fd88cde254d32923e8b1e8a7b_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/preserve/README.md"));

        // line 1
        echo "# preserve [![NPM version](https://badge.fury.io/js/preserve.svg)](http://badge.fury.io/js/preserve)

> Temporarily substitute tokens in the given `string` with placeholders, then put them back after transforming the string.

Useful for protecting tokens, like templates in HTML, from being mutated when the string is transformed in some way, like from a formatter/beautifier.

**Example without `preserve`**

Let's say you want to use [js-beautify] on a string of html with Lo-Dash/Underscore templates, such as: `<ul><li><%= name %></li></ul>`:

js-beautify will render the template unusable (and apply incorrect formatting because of the unfamiliar syntax from the Lo-Dash template):

```html
<ul>
  <li>
    <%=n ame %>
  </li>
</ul>
```

**Example with `preserve`**

Correct.

```html
<ul>
  <li><%= name %></li>
</ul>
```

For the record, this is just a random example, I've had very few issues with js-beautify in general. But with or without js-beautify, this kind of token mangling does happen sometimes when you use formatters, beautifiers or similar tools.

## Install
## Install with [npm](npmjs.org)

```bash
npm i preserve --save
```

## Run tests

```bash
npm test
```

## API
### [.before](index.js#L23)

Replace tokens in `str` with a temporary, heuristic placeholder.

* `str` **{String}**    
* `returns` **{String}**: String with placeholders.  

```js
tokens.before('{a\\\\,b}');
//=> '{__ID1__}'
```

### [.after](index.js#L44)

Replace placeholders in `str` with original tokens.

* `str` **{String}**: String with placeholders    
* `returns` **{String}** `str`: String with original tokens.  

```js
tokens.after('{__ID1__}');
//=> '{a\\\\,b}'
```


## Contributing
Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/preserve/issues)

## Author

**Jon Schlinkert**
 
+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert) 

## License
Copyright (c) 2015-2015, Jon Schlinkert.
Released under the MIT license

***

_This file was generated by [verb](https://github.com/assemble/verb) on January 10, 2015._

[js-beautify]: https://github.com/beautify-web/js-beautify";
        
        $__internal_131d38353579464d037a76dbc314b6ea6f799d1fd88cde254d32923e8b1e8a7b->leave($__internal_131d38353579464d037a76dbc314b6ea6f799d1fd88cde254d32923e8b1e8a7b_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/preserve/README.md";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# preserve [![NPM version](https://badge.fury.io/js/preserve.svg)](http://badge.fury.io/js/preserve)

> Temporarily substitute tokens in the given `string` with placeholders, then put them back after transforming the string.

Useful for protecting tokens, like templates in HTML, from being mutated when the string is transformed in some way, like from a formatter/beautifier.

**Example without `preserve`**

Let's say you want to use [js-beautify] on a string of html with Lo-Dash/Underscore templates, such as: `<ul><li><%= name %></li></ul>`:

js-beautify will render the template unusable (and apply incorrect formatting because of the unfamiliar syntax from the Lo-Dash template):

```html
<ul>
  <li>
    <%=n ame %>
  </li>
</ul>
```

**Example with `preserve`**

Correct.

```html
<ul>
  <li><%= name %></li>
</ul>
```

For the record, this is just a random example, I've had very few issues with js-beautify in general. But with or without js-beautify, this kind of token mangling does happen sometimes when you use formatters, beautifiers or similar tools.

## Install
## Install with [npm](npmjs.org)

```bash
npm i preserve --save
```

## Run tests

```bash
npm test
```

## API
### [.before](index.js#L23)

Replace tokens in `str` with a temporary, heuristic placeholder.

* `str` **{String}**    
* `returns` **{String}**: String with placeholders.  

```js
tokens.before('{a\\\\,b}');
//=> '{__ID1__}'
```

### [.after](index.js#L44)

Replace placeholders in `str` with original tokens.

* `str` **{String}**: String with placeholders    
* `returns` **{String}** `str`: String with original tokens.  

```js
tokens.after('{__ID1__}');
//=> '{a\\\\,b}'
```


## Contributing
Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/preserve/issues)

## Author

**Jon Schlinkert**
 
+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert) 

## License
Copyright (c) 2015-2015, Jon Schlinkert.
Released under the MIT license

***

_This file was generated by [verb](https://github.com/assemble/verb) on January 10, 2015._

[js-beautify]: https://github.com/beautify-web/js-beautify", "node_modules/preserve/README.md", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/preserve/README.md");
    }
}
