<?php

/* node_modules/center-align/README.md */
class __TwigTemplate_bf5ae33ad6807fe7158e6f36bc19cf2b5a707fa583fa5f32fe88d8f6b8751630 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_6d46a19f1a1a39fd5a6f4e80440597939d38b50d1ff2c24b9dc9a68e9640d3b3 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_6d46a19f1a1a39fd5a6f4e80440597939d38b50d1ff2c24b9dc9a68e9640d3b3->enter($__internal_6d46a19f1a1a39fd5a6f4e80440597939d38b50d1ff2c24b9dc9a68e9640d3b3_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/center-align/README.md"));

        // line 1
        echo "# center-align [![NPM version](https://badge.fury.io/js/center-align.svg)](http://badge.fury.io/js/center-align)

> Center-align the text in a string.

Install with [npm](https://www.npmjs.com/)

```sh
\$ npm i center-align --save
```

## Usage

```js
var centerAlign = require('center-align');
```

**Example**

If used on the following:

```
Lorem ipsum dolor sit amet,
consectetur adipiscing
elit, sed do eiusmod tempor incididunt
ut labore et dolore
magna aliqua. Ut enim ad minim
veniam, quis
```

The result would be:

```
     Lorem ipsum dolor sit amet,
        consectetur adipiscing
elit, sed do eiusmod tempor incididunt
         ut labore et dolore
    magna aliqua. Ut enim ad minim
             veniam, quis
```

## Related projects

* [align-text](https://www.npmjs.com/package/align-text): Align the text in a string. | [homepage](https://github.com/jonschlinkert/align-text)
* [justified](https://www.npmjs.com/package/justified): Wrap words to a specified length and justified the text. | [homepage](https://github.com/jonschlinkert/justified)
* [right-align](https://www.npmjs.com/package/right-align): Right-align the text in a string. | [homepage](https://github.com/jonschlinkert/right-align)
* [word-wrap](https://www.npmjs.com/package/word-wrap): Wrap words to a specified length. | [homepage](https://github.com/jonschlinkert/word-wrap)

## Running tests

Install dev dependencies:

```sh
\$ npm i -d && npm test
```

## Contributing

Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/center-align/issues/new).

## Author

**Jon Schlinkert**

+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert)

## License

Copyright © 2015 Jon Schlinkert
Released under the MIT license.

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on October 27, 2015._";
        
        $__internal_6d46a19f1a1a39fd5a6f4e80440597939d38b50d1ff2c24b9dc9a68e9640d3b3->leave($__internal_6d46a19f1a1a39fd5a6f4e80440597939d38b50d1ff2c24b9dc9a68e9640d3b3_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/center-align/README.md";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# center-align [![NPM version](https://badge.fury.io/js/center-align.svg)](http://badge.fury.io/js/center-align)

> Center-align the text in a string.

Install with [npm](https://www.npmjs.com/)

```sh
\$ npm i center-align --save
```

## Usage

```js
var centerAlign = require('center-align');
```

**Example**

If used on the following:

```
Lorem ipsum dolor sit amet,
consectetur adipiscing
elit, sed do eiusmod tempor incididunt
ut labore et dolore
magna aliqua. Ut enim ad minim
veniam, quis
```

The result would be:

```
     Lorem ipsum dolor sit amet,
        consectetur adipiscing
elit, sed do eiusmod tempor incididunt
         ut labore et dolore
    magna aliqua. Ut enim ad minim
             veniam, quis
```

## Related projects

* [align-text](https://www.npmjs.com/package/align-text): Align the text in a string. | [homepage](https://github.com/jonschlinkert/align-text)
* [justified](https://www.npmjs.com/package/justified): Wrap words to a specified length and justified the text. | [homepage](https://github.com/jonschlinkert/justified)
* [right-align](https://www.npmjs.com/package/right-align): Right-align the text in a string. | [homepage](https://github.com/jonschlinkert/right-align)
* [word-wrap](https://www.npmjs.com/package/word-wrap): Wrap words to a specified length. | [homepage](https://github.com/jonschlinkert/word-wrap)

## Running tests

Install dev dependencies:

```sh
\$ npm i -d && npm test
```

## Contributing

Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/center-align/issues/new).

## Author

**Jon Schlinkert**

+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert)

## License

Copyright © 2015 Jon Schlinkert
Released under the MIT license.

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on October 27, 2015._", "node_modules/center-align/README.md", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/center-align/README.md");
    }
}
