<?php

/* node_modules/buffer/bin/update-authors.sh */
class __TwigTemplate_1349011f2a6d8e69dde9d2cf231d375995821a3f026ca93c32a8ec2f04a48214 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_b1cafede64a3daa3aceede379c1edde9d226f1102a738cd89cfe7fabdd831897 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_b1cafede64a3daa3aceede379c1edde9d226f1102a738cd89cfe7fabdd831897->enter($__internal_b1cafede64a3daa3aceede379c1edde9d226f1102a738cd89cfe7fabdd831897_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/buffer/bin/update-authors.sh"));

        // line 1
        echo "#!/bin/sh
# Update AUTHORS.md based on git history.

git log --reverse --format='%aN (%aE)' | perl -we '
BEGIN {
  %seen = (), @authors = ();
}
while (<>) {
  next if \$seen{\$_};
  next if /(support\\@greenkeeper.io)/;
  next if /(dcousens\\@users.noreply.github.com)/;
  next if /(cmetcalf\\@appgeo.com)/;
  \$seen{\$_} = push @authors, \"- \", \$_;
}
END {
  print \"# Authors\\n\\n\";
  print \"#### Ordered by first contribution.\\n\\n\";
  print @authors, \"\\n\";
  print \"#### Generated by bin/update-authors.sh.\\n\";
}
' > AUTHORS.md
";
        
        $__internal_b1cafede64a3daa3aceede379c1edde9d226f1102a738cd89cfe7fabdd831897->leave($__internal_b1cafede64a3daa3aceede379c1edde9d226f1102a738cd89cfe7fabdd831897_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/buffer/bin/update-authors.sh";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("#!/bin/sh
# Update AUTHORS.md based on git history.

git log --reverse --format='%aN (%aE)' | perl -we '
BEGIN {
  %seen = (), @authors = ();
}
while (<>) {
  next if \$seen{\$_};
  next if /(support\\@greenkeeper.io)/;
  next if /(dcousens\\@users.noreply.github.com)/;
  next if /(cmetcalf\\@appgeo.com)/;
  \$seen{\$_} = push @authors, \"- \", \$_;
}
END {
  print \"# Authors\\n\\n\";
  print \"#### Ordered by first contribution.\\n\\n\";
  print @authors, \"\\n\";
  print \"#### Generated by bin/update-authors.sh.\\n\";
}
' > AUTHORS.md
", "node_modules/buffer/bin/update-authors.sh", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/buffer/bin/update-authors.sh");
    }
}
