<?php

/* node_modules/fsevents/build/binding.Makefile */
class __TwigTemplate_3d4e7b0c6f136b96629b1cfb1837f02be71400b8befa24a01f1645dfb25e22b2 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_ddaf4c4f94cb4091eb6a5c9597eb5115e7438e71989b33288a09291dccb58832 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_ddaf4c4f94cb4091eb6a5c9597eb5115e7438e71989b33288a09291dccb58832->enter($__internal_ddaf4c4f94cb4091eb6a5c9597eb5115e7438e71989b33288a09291dccb58832_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/fsevents/build/binding.Makefile"));

        // line 1
        echo "# This file is generated by gyp; do not edit.

export builddir_name ?= ./build/.
.PHONY: all
all:
\t\$(MAKE)  fse action_after_build
";
        
        $__internal_ddaf4c4f94cb4091eb6a5c9597eb5115e7438e71989b33288a09291dccb58832->leave($__internal_ddaf4c4f94cb4091eb6a5c9597eb5115e7438e71989b33288a09291dccb58832_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/fsevents/build/binding.Makefile";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# This file is generated by gyp; do not edit.

export builddir_name ?= ./build/.
.PHONY: all
all:
\t\$(MAKE)  fse action_after_build
", "node_modules/fsevents/build/binding.Makefile", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/fsevents/build/binding.Makefile");
    }
}
