<?php

/* node_modules/arr-diff/README.md */
class __TwigTemplate_8d574059828839d900fd88848fb57e5eaac65753d1b4f0d50b7076648b788719 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_568bb90e44564e344e63df5d311bbd6e75de05bf83ae8a093039a21e12fb308a = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_568bb90e44564e344e63df5d311bbd6e75de05bf83ae8a093039a21e12fb308a->enter($__internal_568bb90e44564e344e63df5d311bbd6e75de05bf83ae8a093039a21e12fb308a_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/arr-diff/README.md"));

        // line 1
        echo "# arr-diff [![NPM version](https://img.shields.io/npm/v/arr-diff.svg)](https://www.npmjs.com/package/arr-diff) [![Build Status](https://img.shields.io/travis/jonschlinkert/base.svg)](https://travis-ci.org/jonschlinkert/base)

> Returns an array with only the unique values from the first array, by excluding all values from additional arrays using strict equality for comparisons.

## Install

Install with [npm](https://www.npmjs.com/)

```sh
\$ npm i arr-diff --save
```
Install with [bower](http://bower.io/)

```sh
\$ bower install arr-diff --save
```

## API

### [diff](index.js#L33)

Return the difference between the first array and additional arrays.

**Params**

* `a` **{Array}**
* `b` **{Array}**
* `returns` **{Array}**

**Example**

```js
var diff = require('arr-diff');

var a = ['a', 'b', 'c', 'd'];
var b = ['b', 'c'];

console.log(diff(a, b))
//=> ['a', 'd']
```

## Related projects

* [arr-flatten](https://www.npmjs.com/package/arr-flatten): Recursively flatten an array or arrays. This is the fastest implementation of array flatten. | [homepage](https://github.com/jonschlinkert/arr-flatten)
* [array-filter](https://www.npmjs.com/package/array-filter): Array#filter for older browsers. | [homepage](https://github.com/juliangruber/array-filter)
* [array-intersection](https://www.npmjs.com/package/array-intersection): Return an array with the unique values present in _all_ given arrays using strict equality… [more](https://www.npmjs.com/package/array-intersection) | [homepage](https://github.com/jonschlinkert/array-intersection)

## Running tests

Install dev dependencies:

```sh
\$ npm i -d && npm test
```

## Contributing

Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/arr-diff/issues/new).

## Author

**Jon Schlinkert**

+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert)

## License

Copyright © 2015 [Jon Schlinkert](https://github.com/jonschlinkert)
Released under the MIT license.

***

_This file was generated by [verb](https://github.com/verbose/verb) on Sat Dec 05 2015 23:24:53 GMT-0500 (EST)._
";
        
        $__internal_568bb90e44564e344e63df5d311bbd6e75de05bf83ae8a093039a21e12fb308a->leave($__internal_568bb90e44564e344e63df5d311bbd6e75de05bf83ae8a093039a21e12fb308a_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/arr-diff/README.md";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# arr-diff [![NPM version](https://img.shields.io/npm/v/arr-diff.svg)](https://www.npmjs.com/package/arr-diff) [![Build Status](https://img.shields.io/travis/jonschlinkert/base.svg)](https://travis-ci.org/jonschlinkert/base)

> Returns an array with only the unique values from the first array, by excluding all values from additional arrays using strict equality for comparisons.

## Install

Install with [npm](https://www.npmjs.com/)

```sh
\$ npm i arr-diff --save
```
Install with [bower](http://bower.io/)

```sh
\$ bower install arr-diff --save
```

## API

### [diff](index.js#L33)

Return the difference between the first array and additional arrays.

**Params**

* `a` **{Array}**
* `b` **{Array}**
* `returns` **{Array}**

**Example**

```js
var diff = require('arr-diff');

var a = ['a', 'b', 'c', 'd'];
var b = ['b', 'c'];

console.log(diff(a, b))
//=> ['a', 'd']
```

## Related projects

* [arr-flatten](https://www.npmjs.com/package/arr-flatten): Recursively flatten an array or arrays. This is the fastest implementation of array flatten. | [homepage](https://github.com/jonschlinkert/arr-flatten)
* [array-filter](https://www.npmjs.com/package/array-filter): Array#filter for older browsers. | [homepage](https://github.com/juliangruber/array-filter)
* [array-intersection](https://www.npmjs.com/package/array-intersection): Return an array with the unique values present in _all_ given arrays using strict equality… [more](https://www.npmjs.com/package/array-intersection) | [homepage](https://github.com/jonschlinkert/array-intersection)

## Running tests

Install dev dependencies:

```sh
\$ npm i -d && npm test
```

## Contributing

Pull requests and stars are always welcome. For bugs and feature requests, [please create an issue](https://github.com/jonschlinkert/arr-diff/issues/new).

## Author

**Jon Schlinkert**

+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert)

## License

Copyright © 2015 [Jon Schlinkert](https://github.com/jonschlinkert)
Released under the MIT license.

***

_This file was generated by [verb](https://github.com/verbose/verb) on Sat Dec 05 2015 23:24:53 GMT-0500 (EST)._
", "node_modules/arr-diff/README.md", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/arr-diff/README.md");
    }
}
