<?php

/* node_modules/is-primitive/README.md */
class __TwigTemplate_6d85a42dc551b4b053087fa36ac00e70b9474f8e21cccc5ce28666f2a7a64f3c extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_a9d85a74e1bd5dd435568df7083d238b501f87dfd96d29e0125ff34f2e64a59f = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_a9d85a74e1bd5dd435568df7083d238b501f87dfd96d29e0125ff34f2e64a59f->enter($__internal_a9d85a74e1bd5dd435568df7083d238b501f87dfd96d29e0125ff34f2e64a59f_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/is-primitive/README.md"));

        // line 1
        echo "# is-primitive [![NPM version](https://badge.fury.io/js/is-primitive.svg)](http://badge.fury.io/js/is-primitive)  [![Build Status](https://travis-ci.org/jonschlinkert/is-primitive.svg)](https://travis-ci.org/jonschlinkert/is-primitive) 

> Returns `true` if the value is a primitive. 

## Install with [npm](npmjs.org)

```bash
npm i is-primitive --save
```

## Running tests
Install dev dependencies.

```bash
npm i -d && npm test
```

## Usage

```js
var isPrimitive = require('is-primitive');
isPrimitive('abc');
//=> true

isPrimitive(42);
//=> true

isPrimitive(false);
//=> true

isPrimitive(true);
//=> true

isPrimitive({});
//=> false

isPrimitive([]);
//=> false

isPrimitive(function(){});
//=> false
```

## Author

**Jon Schlinkert**
 
+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert) 

## License
Copyright (c) 2014-2015 Jon Schlinkert  
Released under the MIT license

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on March 16, 2015._";
        
        $__internal_a9d85a74e1bd5dd435568df7083d238b501f87dfd96d29e0125ff34f2e64a59f->leave($__internal_a9d85a74e1bd5dd435568df7083d238b501f87dfd96d29e0125ff34f2e64a59f_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/is-primitive/README.md";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# is-primitive [![NPM version](https://badge.fury.io/js/is-primitive.svg)](http://badge.fury.io/js/is-primitive)  [![Build Status](https://travis-ci.org/jonschlinkert/is-primitive.svg)](https://travis-ci.org/jonschlinkert/is-primitive) 

> Returns `true` if the value is a primitive. 

## Install with [npm](npmjs.org)

```bash
npm i is-primitive --save
```

## Running tests
Install dev dependencies.

```bash
npm i -d && npm test
```

## Usage

```js
var isPrimitive = require('is-primitive');
isPrimitive('abc');
//=> true

isPrimitive(42);
//=> true

isPrimitive(false);
//=> true

isPrimitive(true);
//=> true

isPrimitive({});
//=> false

isPrimitive([]);
//=> false

isPrimitive(function(){});
//=> false
```

## Author

**Jon Schlinkert**
 
+ [github/jonschlinkert](https://github.com/jonschlinkert)
+ [twitter/jonschlinkert](http://twitter.com/jonschlinkert) 

## License
Copyright (c) 2014-2015 Jon Schlinkert  
Released under the MIT license

***

_This file was generated by [verb-cli](https://github.com/assemble/verb-cli) on March 16, 2015._", "node_modules/is-primitive/README.md", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/is-primitive/README.md");
    }
}
