<?php

/* node_modules/fsevents/build/action_after_build.target.mk */
class __TwigTemplate_7542c06ce717152b1a537a51721905c9e2ad484fe42bd83947dc14d5e0e40835 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_4c911352cb621cad928453fb3a378cbcb36f00e0f5c506223815d1b6ab8f6891 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_4c911352cb621cad928453fb3a378cbcb36f00e0f5c506223815d1b6ab8f6891->enter($__internal_4c911352cb621cad928453fb3a378cbcb36f00e0f5c506223815d1b6ab8f6891_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/fsevents/build/action_after_build.target.mk"));

        // line 1
        echo "# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := action_after_build
### Generated for copy rule.
/Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node: TOOLSET := \$(TOOLSET)
/Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node: \$(builddir)/fse.node FORCE_DO_CMD
\t\$(call do_cmd,copy)

all_deps += /Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node
binding_gyp_action_after_build_target_copies = /Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node

### Rules for final target.
# Build our special outputs first.
\$(obj).target/action_after_build.stamp: | \$(binding_gyp_action_after_build_target_copies)

# Preserve order dependency of special output on deps.
\$(binding_gyp_action_after_build_target_copies): | \$(builddir)/fse.node

\$(obj).target/action_after_build.stamp: TOOLSET := \$(TOOLSET)
\$(obj).target/action_after_build.stamp: \$(builddir)/fse.node FORCE_DO_CMD
\t\$(call do_cmd,touch)

all_deps += \$(obj).target/action_after_build.stamp
# Add target alias
.PHONY: action_after_build
action_after_build: \$(obj).target/action_after_build.stamp

# Add target alias to \"all\" target.
.PHONY: all
all: action_after_build

";
        
        $__internal_4c911352cb621cad928453fb3a378cbcb36f00e0f5c506223815d1b6ab8f6891->leave($__internal_4c911352cb621cad928453fb3a378cbcb36f00e0f5c506223815d1b6ab8f6891_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/fsevents/build/action_after_build.target.mk";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := action_after_build
### Generated for copy rule.
/Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node: TOOLSET := \$(TOOLSET)
/Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node: \$(builddir)/fse.node FORCE_DO_CMD
\t\$(call do_cmd,copy)

all_deps += /Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node
binding_gyp_action_after_build_target_copies = /Users/eshanker/Code/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node

### Rules for final target.
# Build our special outputs first.
\$(obj).target/action_after_build.stamp: | \$(binding_gyp_action_after_build_target_copies)

# Preserve order dependency of special output on deps.
\$(binding_gyp_action_after_build_target_copies): | \$(builddir)/fse.node

\$(obj).target/action_after_build.stamp: TOOLSET := \$(TOOLSET)
\$(obj).target/action_after_build.stamp: \$(builddir)/fse.node FORCE_DO_CMD
\t\$(call do_cmd,touch)

all_deps += \$(obj).target/action_after_build.stamp
# Add target alias
.PHONY: action_after_build
action_after_build: \$(obj).target/action_after_build.stamp

# Add target alias to \"all\" target.
.PHONY: all
all: action_after_build

", "node_modules/fsevents/build/action_after_build.target.mk", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/fsevents/build/action_after_build.target.mk");
    }
}
