<?php

/* node_modules/regexpu-core/data/character-class-escape-sets.js */
class __TwigTemplate_4b3817310c76531802bb565331e66f4135ac5b4a405043f537b46b0d1ccc5935 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_b34716ea46bedae2e650b9e675f559aa3bff7b79e8a26d315f79023d0a19b3a3 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_b34716ea46bedae2e650b9e675f559aa3bff7b79e8a26d315f79023d0a19b3a3->enter($__internal_b34716ea46bedae2e650b9e675f559aa3bff7b79e8a26d315f79023d0a19b3a3_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "node_modules/regexpu-core/data/character-class-escape-sets.js"));

        // line 1
        echo "// Generated by `/scripts/character-class-escape-sets.js`. Do not edit.
var regenerate = require('regenerate');

exports.REGULAR = {
\t'd': regenerate()
\t\t.addRange(0x30, 0x39),
\t'D': regenerate()
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0xFFFF),
\t's': regenerate(0x20, 0xA0, 0x1680, 0x202F, 0x205F, 0x3000, 0xFEFF)
\t\t.addRange(0x9, 0xD)
\t\t.addRange(0x2000, 0x200A)
\t\t.addRange(0x2028, 0x2029),
\t'S': regenerate()
\t\t.addRange(0x0, 0x8)
\t\t.addRange(0xE, 0x1F)
\t\t.addRange(0x21, 0x9F)
\t\t.addRange(0xA1, 0x167F)
\t\t.addRange(0x1681, 0x1FFF)
\t\t.addRange(0x200B, 0x2027)
\t\t.addRange(0x202A, 0x202E)
\t\t.addRange(0x2030, 0x205E)
\t\t.addRange(0x2060, 0x2FFF)
\t\t.addRange(0x3001, 0xFEFE)
\t\t.addRange(0xFF00, 0xFFFF),
\t'w': regenerate(0x5F)
\t\t.addRange(0x30, 0x39)
\t\t.addRange(0x41, 0x5A)
\t\t.addRange(0x61, 0x7A),
\t'W': regenerate(0x60)
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x40)
\t\t.addRange(0x5B, 0x5E)
\t\t.addRange(0x7B, 0xFFFF)
};

exports.UNICODE = {
\t'd': regenerate()
\t\t.addRange(0x30, 0x39),
\t'D': regenerate()
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x10FFFF),
\t's': regenerate(0x20, 0xA0, 0x1680, 0x202F, 0x205F, 0x3000, 0xFEFF)
\t\t.addRange(0x9, 0xD)
\t\t.addRange(0x2000, 0x200A)
\t\t.addRange(0x2028, 0x2029),
\t'S': regenerate()
\t\t.addRange(0x0, 0x8)
\t\t.addRange(0xE, 0x1F)
\t\t.addRange(0x21, 0x9F)
\t\t.addRange(0xA1, 0x167F)
\t\t.addRange(0x1681, 0x1FFF)
\t\t.addRange(0x200B, 0x2027)
\t\t.addRange(0x202A, 0x202E)
\t\t.addRange(0x2030, 0x205E)
\t\t.addRange(0x2060, 0x2FFF)
\t\t.addRange(0x3001, 0xFEFE)
\t\t.addRange(0xFF00, 0x10FFFF),
\t'w': regenerate(0x5F)
\t\t.addRange(0x30, 0x39)
\t\t.addRange(0x41, 0x5A)
\t\t.addRange(0x61, 0x7A),
\t'W': regenerate(0x60)
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x40)
\t\t.addRange(0x5B, 0x5E)
\t\t.addRange(0x7B, 0x10FFFF)
};

exports.UNICODE_IGNORE_CASE = {
\t'd': regenerate()
\t\t.addRange(0x30, 0x39),
\t'D': regenerate()
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x10FFFF),
\t's': regenerate(0x20, 0xA0, 0x1680, 0x202F, 0x205F, 0x3000, 0xFEFF)
\t\t.addRange(0x9, 0xD)
\t\t.addRange(0x2000, 0x200A)
\t\t.addRange(0x2028, 0x2029),
\t'S': regenerate()
\t\t.addRange(0x0, 0x8)
\t\t.addRange(0xE, 0x1F)
\t\t.addRange(0x21, 0x9F)
\t\t.addRange(0xA1, 0x167F)
\t\t.addRange(0x1681, 0x1FFF)
\t\t.addRange(0x200B, 0x2027)
\t\t.addRange(0x202A, 0x202E)
\t\t.addRange(0x2030, 0x205E)
\t\t.addRange(0x2060, 0x2FFF)
\t\t.addRange(0x3001, 0xFEFE)
\t\t.addRange(0xFF00, 0x10FFFF),
\t'w': regenerate(0x5F, 0x17F, 0x212A)
\t\t.addRange(0x30, 0x39)
\t\t.addRange(0x41, 0x5A)
\t\t.addRange(0x61, 0x7A),
\t'W': regenerate(0x4B, 0x53, 0x60)
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x40)
\t\t.addRange(0x5B, 0x5E)
\t\t.addRange(0x7B, 0x10FFFF)
};
";
        
        $__internal_b34716ea46bedae2e650b9e675f559aa3bff7b79e8a26d315f79023d0a19b3a3->leave($__internal_b34716ea46bedae2e650b9e675f559aa3bff7b79e8a26d315f79023d0a19b3a3_prof);

    }

    public function getTemplateName()
    {
        return "node_modules/regexpu-core/data/character-class-escape-sets.js";
    }

    public function getDebugInfo()
    {
        return array (  22 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("// Generated by `/scripts/character-class-escape-sets.js`. Do not edit.
var regenerate = require('regenerate');

exports.REGULAR = {
\t'd': regenerate()
\t\t.addRange(0x30, 0x39),
\t'D': regenerate()
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0xFFFF),
\t's': regenerate(0x20, 0xA0, 0x1680, 0x202F, 0x205F, 0x3000, 0xFEFF)
\t\t.addRange(0x9, 0xD)
\t\t.addRange(0x2000, 0x200A)
\t\t.addRange(0x2028, 0x2029),
\t'S': regenerate()
\t\t.addRange(0x0, 0x8)
\t\t.addRange(0xE, 0x1F)
\t\t.addRange(0x21, 0x9F)
\t\t.addRange(0xA1, 0x167F)
\t\t.addRange(0x1681, 0x1FFF)
\t\t.addRange(0x200B, 0x2027)
\t\t.addRange(0x202A, 0x202E)
\t\t.addRange(0x2030, 0x205E)
\t\t.addRange(0x2060, 0x2FFF)
\t\t.addRange(0x3001, 0xFEFE)
\t\t.addRange(0xFF00, 0xFFFF),
\t'w': regenerate(0x5F)
\t\t.addRange(0x30, 0x39)
\t\t.addRange(0x41, 0x5A)
\t\t.addRange(0x61, 0x7A),
\t'W': regenerate(0x60)
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x40)
\t\t.addRange(0x5B, 0x5E)
\t\t.addRange(0x7B, 0xFFFF)
};

exports.UNICODE = {
\t'd': regenerate()
\t\t.addRange(0x30, 0x39),
\t'D': regenerate()
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x10FFFF),
\t's': regenerate(0x20, 0xA0, 0x1680, 0x202F, 0x205F, 0x3000, 0xFEFF)
\t\t.addRange(0x9, 0xD)
\t\t.addRange(0x2000, 0x200A)
\t\t.addRange(0x2028, 0x2029),
\t'S': regenerate()
\t\t.addRange(0x0, 0x8)
\t\t.addRange(0xE, 0x1F)
\t\t.addRange(0x21, 0x9F)
\t\t.addRange(0xA1, 0x167F)
\t\t.addRange(0x1681, 0x1FFF)
\t\t.addRange(0x200B, 0x2027)
\t\t.addRange(0x202A, 0x202E)
\t\t.addRange(0x2030, 0x205E)
\t\t.addRange(0x2060, 0x2FFF)
\t\t.addRange(0x3001, 0xFEFE)
\t\t.addRange(0xFF00, 0x10FFFF),
\t'w': regenerate(0x5F)
\t\t.addRange(0x30, 0x39)
\t\t.addRange(0x41, 0x5A)
\t\t.addRange(0x61, 0x7A),
\t'W': regenerate(0x60)
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x40)
\t\t.addRange(0x5B, 0x5E)
\t\t.addRange(0x7B, 0x10FFFF)
};

exports.UNICODE_IGNORE_CASE = {
\t'd': regenerate()
\t\t.addRange(0x30, 0x39),
\t'D': regenerate()
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x10FFFF),
\t's': regenerate(0x20, 0xA0, 0x1680, 0x202F, 0x205F, 0x3000, 0xFEFF)
\t\t.addRange(0x9, 0xD)
\t\t.addRange(0x2000, 0x200A)
\t\t.addRange(0x2028, 0x2029),
\t'S': regenerate()
\t\t.addRange(0x0, 0x8)
\t\t.addRange(0xE, 0x1F)
\t\t.addRange(0x21, 0x9F)
\t\t.addRange(0xA1, 0x167F)
\t\t.addRange(0x1681, 0x1FFF)
\t\t.addRange(0x200B, 0x2027)
\t\t.addRange(0x202A, 0x202E)
\t\t.addRange(0x2030, 0x205E)
\t\t.addRange(0x2060, 0x2FFF)
\t\t.addRange(0x3001, 0xFEFE)
\t\t.addRange(0xFF00, 0x10FFFF),
\t'w': regenerate(0x5F, 0x17F, 0x212A)
\t\t.addRange(0x30, 0x39)
\t\t.addRange(0x41, 0x5A)
\t\t.addRange(0x61, 0x7A),
\t'W': regenerate(0x4B, 0x53, 0x60)
\t\t.addRange(0x0, 0x2F)
\t\t.addRange(0x3A, 0x40)
\t\t.addRange(0x5B, 0x5E)
\t\t.addRange(0x7B, 0x10FFFF)
};
", "node_modules/regexpu-core/data/character-class-escape-sets.js", "/Users/mikel/Developer/DEV/FrontFoundation/tests/app/node_modules/regexpu-core/data/character-class-escape-sets.js");
    }
}
